# Generated by Django 5.2.6 on 2025-10-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papercheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='questions',
        ),
    ]
