# Generated by Django 5.2.6 on 2025-10-11 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papercheck', '0002_remove_questionpaper_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='answer_sheets/')),
                ('marks_obtained', models.FloatField(blank=True, null=True)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='papercheck.questionpaper')),
            ],
        ),
    ]
