# Generated by Django 5.2.6 on 2025-10-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_aid', '0002_visualaid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualaid',
            name='mermaid_code',
        ),
        migrations.RemoveField(
            model_name='visualaid',
            name='question',
        ),
        migrations.AddField(
            model_name='visualaid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='visual-aid/'),
        ),
    ]
