# Generated by Django 5.2.6 on 2025-09-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_profile_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='grade',
        ),
        migrations.AddField(
            model_name='profile',
            name='grades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
