# Generated by Django 5.2.6 on 2025-09-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_remove_profile_grade_profile_grades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='grades',
            new_name='grade',
        ),
    ]
