# Generated by Django 5.2.6 on 2025-09-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_rename_grades_profile_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='grade',
            new_name='grades',
        ),
    ]
